part 2 tasks - all in one pull request
js-tasks-ru/vue-20240924_denis457 pull request #3
Opened 2024-10-12 16:49 UTC by netfisher777

2024-10-12 16:49 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-13 22:44 UTC, ShGKme requested changes

2024-10-13 22:44 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +        <label><input type="radio" name="operator" :value="operator.value" :checked="selectedOperator.value == operator.value" @input="handleOperatorChange(operator)"/>{{ operator.icon }}</label>
Вместо ручной привязки `:checked` и обработки события `@input`, здесь должна использоваться директива двустороннего связывания `v-model`. Это сильно проще и явно показывает связывание элемента формы с данными.

2024-10-13 22:44 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +        <label><input type="radio" name="operator" :value="operator.value" :checked="selectedOperator.value == operator.value" @input="handleOperatorChange(operator)"/>{{ operator.icon }}</label>
Все `ref`-ы в шаблоне автоматически разворачиваются. Потому там уже не нужно обращаться к `.value`. В итоге идёт обращение к `selectedOperator.value.value`, где изначально лежит `undefined` (потому что у строки нет такого поля).

2024-10-13 22:44 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +              :checked="checked"
Сейчас выбранность радиокнопки определяется дважды - один раз `v-model` привязывает через `selectedMeetup`, и один раз `checked` через `meetupIdInfos[].checked`. В итоге есть два источника для этого состояния, которые могут друг другу противоречить.

2024-10-13 22:44 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +              :checked="checked"
При этом для хранения единицы информации (какой митап выбран), хранится по одному свойству в каждом `meetupInfop[]`, то есть 5 флагов.

2024-10-13 22:44 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +              :checked="checked"
Должен быть только один корректный источник этого состояния.

2024-10-15 06:19 UTC, netfisher777 commented on 02-basics-2/30-calculator/CalculatorApp.js
> +        <label><input type="radio" name="operator" :value="operator.value" :checked="selectedOperator.value == operator.value" @input="handleOperatorChange(operator)"/>{{ operator.icon }}</label>
По поводу обращения к selectedOperator.value мной в шаблоне - я и рассчитывал, что он развернет это в selectedOperator.value.value, потому что у меня в массиве объектов как раз свойство value есть:
const operators = [
      {
        value: OPERATOR_VALUE.SUM,
        sign: '+',
        icon: '➕',
      }
...

2024-10-15 06:24 UTC, netfisher777 commented on 02-basics-2/30-calculator/CalculatorApp.js
> +        <label><input type="radio" name="operator" :value="operator.value" :checked="selectedOperator.value == operator.value" @input="handleOperatorChange(operator)"/>{{ operator.icon }}</label>
Поменяю название свойства на code, чтобы в заблуждение не вводило

2024-10-15 09:27 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-15 09:29 UTC, netfisher777 commented
Поправил все замечания, просьба проревьюить

2024-10-20 20:36 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +        <label><input type="radio" name="operator" :value="operator.value" :checked="selectedOperator.value == operator.value" @input="handleOperatorChange(operator)"/>{{ operator.icon }}</label>
Понял, сорри, пропустил

2024-10-20 20:53 UTC, ShGKme requested changes
Осталась маленькая проблема с прошлого ревью

2024-10-20 20:53 UTC, ShGKme commented on 02-basics-2/30-calculator/CalculatorApp.js
> +        </template>
Осталась проблема с прошлого ревью. Привязка `checked` здесь выполняется дважды - через `v-model` и через `:checked`. Должен быть только `v-model`, он уже привязывает и `checked`, и обработку `@input`

2024-10-20 20:53 UTC, ShGKme commented on 02-basics-2/50-selected-meetup/SelectedMeetupApp.js
> +              :checked="selectedMeetupId == id"
Аналогично

2024-10-28 16:30 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-10-28 16:32 UTC, netfisher777 commented
Поправил

2024-11-01 15:48 UTC, ShGKme approved these changes

2024-11-01 15:49 UTC, merged